import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { fetchFonds, fetchByType, type Fonds } from '../api/archief'
import { Timeline } from '../components/Timeline'
import { Tabs } from '../components/Tabs'
import { Inventaris } from '../components/Inventaris'
import { Persoonsvermeldingen } from '../components/Persoonsvermeldingen'
import { Records } from '../components/Records'
import './GraphPage.css'
